server:
  port: 8123
  servlet:
    # 项目启动域名前缀(上下文)
    context-path: /api
  # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: yu-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture
    username: root
    password: MySQL123
  # redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    connect-timeout: 5000
  # Session 配置 30 天过期和 cookie 过期保持一致
  session:
    store-type: redis
    # 一天86400 * 30
    timeout: 2592000

  # 表示开发环境接入 application-local.yaml 的配置
  profiles:
    active: local
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    # 关闭驼峰命名映射,因为这里我们表就是驼峰式的不需要开启驼峰映射
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名，也可以用 @TableLogic实体类注解
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    # 表示分组
    group:
      # 可以分多个组,这里使用默认分组
      default:
        api-rule: package
        api-rule-resources:
          - com.rainbowsea.yupicturebackend.controller

# 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host: 存储桶的域名 https://xxx.myqcloud.com
#    secretId: 用户密钥的ID或者账户
#    secretKey: 用户密钥的密码
#    region: 表示对象存储桶所在设置的地域名
#    bucket: 存储桶名
